branches:
  only:
  - master
language: python
python: 3.5
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --exclude
  '.gitignore' --exclude 'upload.sh' --acl public-read --delete . s3://www.caxap.design
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E1NMNJQG1HTNRB --paths '/*'
