branches:
  only:
  - master
language: python
python: 3.5
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --exclude
  '.gitignore' --exclude 'upload.sh' --acl public-read --delete . s3://www.caxap.design
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E1NMNJQG1HTNRB --paths '/*'
env:
  global:
  - secure: qnNjJFNK2HqW4+HCUdQ9hILxZzZ+FA3kUUa5rUoB6YtjHqBu6VQy2ImrL2P8jQ+vR8LkLt8MVBN7QBL+DXP1CDTnLs9065blM2pfhaGe51RMF9xq+mcD7HoHv0oNwar7zOsvcdGkrbXDAQ4/ymLNXF/JO4NXTDxygSTk//ceUTK36tQ5MaCekcOPWucsIQyPnF3C52QH2tkoaFpvF0QzuCg0OE7tjJWs7HbPUGCTsbF/JkEdxJS1mLCKK5UXBg5Md0YNtNHNIPiXgItJfneC70IvnMXmCr7Yj8N7fgoA5S5bobSveA8RNTiDWSPdsNo6eEOlFlTQIMvL7NvKda9itV05mYqappNUp/jP5az/Vg48MzF8cjO8l19cNahvItE43zj12xneJ4fyRD43qAb4U7hCpig3nIjQzEAP97YKdn4zYJi9tQ6AY6cn/qG4XaUdPg6wTt0/iaDLdKLzJkYNz4iR3rV6QItJyt/vROyeoWWanoR/PYSw35nOP3NExHS39nHXxvoJjNNKRyZUhp2QraiCTq+J2ZfRsqR99HeaSwhZnP9JBkg2XJ0jzitBrZ0AUSlrQjO2idppNWrRML2QTx8Wc9MBWqaUz34FESiJauTwxWfMgBmWs2fvKcxCiXrldC6HmpYGyiagQy+GuusbfBXFCxCk8q3vO4avIicnRpM=
  - secure: TeEfBF7LGQQsYBzGmM4WWh6l/5exqKSDIYEcAs5cSaZbGbiJ5/W7tQd/iHb4BHANpN7bz1y8jkgrLRA96vyVsS/qV4SLq/Mz8gdOPbd5cdxvCu+qwwI0yF1iindyraFi4K0EUX64pKShCxqG028PgoVCDRwmlzK/HQS3x3dhEfLNJOBZF48ibqp427YN4VNcCrjwCbVITWqCWRoEktFEE/tsRvI2OFaJrh54uTOp3r1GkHm97SZyW0daPoJqDzT7TblSeehXd5jWTsGVSkNVb6ioh+IbcDIwL3b3LMGLF5u2oyC6rPOIVQP/tiSzqQVWq3e1WkgY80t522Yyc+tLOGTwOu+MmzO3R6q73ejCD6BrpfRNcXFh/wwBTaMX53k0MpUfcQyynCRImrrtCyzHBUSx8Z+dieZPDX7rt4uh94z/PmgPxQDeGPKoFEwQAWFufBhZdYQYnV2gv63TQScSXzWvNXuuvf2SNXaHB1oj56Y/rCCpmLmnOpsbeWRVs2D4itrOGsKrQc4dXn+16M0a+QJv4lCAXM4eai3wY107oP5R2VzrgSNzShWH6DX28AR4bac2rHma39sEUthqxQiNgYeqc3hE/eoEhWRii36UvjbFWgvqKeMMXQXlJ54zMFR7Zd5iznPHbT8vIqyZGRLObzWp7mpFGsEPF5KLMINvuCU=
