branches:
  only:
  - master
language: python
python: 3.5
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --exclude
  '.gitignore' --exclude 'upload.sh' --acl public-read --delete . s3://www.caxap.design
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E1NMNJQG1HTNRB --paths '/*'
deploy:
  secret_access_key:
    secure: XTOYnGP9H6U4B9ypTvkDE2sfLVvgiK7gEgfG3ZgJNDfDBXEvVbmy/AIni/gqZuKv4gv4XoFN3gqOILvi2Tn12KdieTTjVWeYy4fAMt9s8TvadqwdimHi0Rg5+co/CDGWays+iKCsBGGyYWdUPd55sVw7vbx6WdGD9KYkhgZiI6iVdmyq4j3oZrcsgS5tFJaKaHAcSX9AeTyPvyQ2nO/v4tKIIbaXE4MSe90krsBvSlAFOFcSAI1of+5R2fxD6stEZskpZL+YfTM9tTfb5UHXQWaV2vMI7wV5QtNECbCEpIQfs69InZEHliDXsoLLmRToM2ZPXodWtkIjMSbcPyVWxZVEhB3wH8AUNjzIvk4KtCVh9VlyEsZEkh9mXGud/VpPLurf8OoFQ3ODQEGIW/XOcdAjI5u+vQ4pAQUgu+2toYy47Bm7NNtXY0CdizaX7j8u2jq9haFJdONrsXINP3lICOdno3A+JQ1eCGjviKn0uM4cKtOq4N1Y/7TWMJ3Celd++qSz4xREAnJcMjC86+aOAiXXYm7AdmkMtVw3rjzK5Yg+vUSoWY6oiyn37PoTEgywhzbs3SiTA+HEWHbLuJ64QE58XCjf71OXHM9cRV51JSahUOpMrMyT5ZvIlAJuPYax22JFkaHnDbmNU8CsxSNkVcdqJ9kv1fheZsaPRNV9gjY=
  access_key_id:
    secure: o7IFELQOGtZ+KZcVMTP+1+pLLKLYxURS1ORKRbpPY9Gkcw5fH2ZxNG4ZN4Hb4es1Rc3xr4eSWzRXwFnLcKatTRVuKwvGsutUmP78UAsl9SF7YD4EcXPm7l5R4oC1P7GNj8f5zg9dNegff55/BA0tOQKvTIu8kZrQ38ki6cWIL/ope6Qh5ZmQ0Cje/kNlgvR5zoCKLcrtTxT/rqSGacjUKe0R0pBnZdnLoyoUYIrUBTxV4NA1TG4svLR+YJdtnqqS9mH4ghrFDYXT5ccOZTlxZVqo07GX//85/lbmlNztQO9lyv+otmKHB/mikXS5gyMjS5HRUM6t8f6SPOtMQL54EabZPP/WlLEBK9azSSaYMANY29K44oHYZxideB3TuUR0OfesPEBhKfG4oxaVDeN9bWS69luMnFvBPaj/6y+hih9yxAvROEB+7lFc7M7jYnP0BGLmvTYTh0llvGRm4KfKhgEtLyEsfLFdTl2APMNNA5b6RWFeW+KNWSZQdLLVx89CFieCcudUIaEKS+OlSRi9dv4oqFVTWeDX0WPNhC6698iJcdGm6qMpOBoHWAE3wCZooAQIpMhIrJzdBf3SuW7ULgttgwLk6iDjZOWMLcfe7xVWf6so9Xbwc5Sx0tGKHTjcRFWy9wO9vqagTPZY+A+LTT6Bb2Su+T5BJNrWSCuhtRg=
